// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3zG1vN2I_oEzhwoZ3mr9MdhTpClbC7fs',
    appId: '1:1072766498193:web:fb33a0318abafffe131630',
    messagingSenderId: '1072766498193',
    projectId: 'camermode-2a49d',
    authDomain: 'camermode-2a49d.firebaseapp.com',
    storageBucket: 'camermode-2a49d.firebasestorage.app',
    measurementId: 'G-SBMY4C342E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARaCxPO9lijOUPbOH-RmbyIliuPpTQzl0',
    appId: '1:1072766498193:android:809fffbcbc98a2d0131630',
    messagingSenderId: '1072766498193',
    projectId: 'camermode-2a49d',
    storageBucket: 'camermode-2a49d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf3c6sj2_o6iKZySlvQTETCMHk6Lh_uvQ',
    appId: '1:1072766498193:ios:67c42abd4732eb30131630',
    messagingSenderId: '1072766498193',
    projectId: 'camermode-2a49d',
    storageBucket: 'camermode-2a49d.firebasestorage.app',
    iosBundleId: 'com.cyriale.camermode',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf3c6sj2_o6iKZySlvQTETCMHk6Lh_uvQ',
    appId: '1:1072766498193:ios:c0fe8a1d822416ac131630',
    messagingSenderId: '1072766498193',
    projectId: 'camermode-2a49d',
    storageBucket: 'camermode-2a49d.firebasestorage.app',
    iosBundleId: 'com.example.camermode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3zG1vN2I_oEzhwoZ3mr9MdhTpClbC7fs',
    appId: '1:1072766498193:web:1ffa98375ff7300b131630',
    messagingSenderId: '1072766498193',
    projectId: 'camermode-2a49d',
    authDomain: 'camermode-2a49d.firebaseapp.com',
    storageBucket: 'camermode-2a49d.firebasestorage.app',
    measurementId: 'G-RZF462E0T5',
  );
}
